name: Alexander Mayorov
description: Front and back-end engineer. JavaScript addict.
meta_description: "Front and back-end engineer. JavaScript addict. Developer advocate and technical evangelist"

aboutPage: true

markdown: kramdown
highlighter: rouge

paginate: 20
baseurl: /
domain_name: 'https://www.majorov.su'
google_analytics: 'UA-44011873-1'
disqus: true
disqus_shortname: 'frontdevops'

# Details for the RSS feed generator
url:            'https://medium.com/@frontman'
author:         'Alexander Mayorov'
authorTwitter:  'frontdevops'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
